// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8G33QaAm6OUKLJwcssNzZ9TsUj0O5-mM',
    appId: '1:871968891803:web:778904448dbccbb902f73e',
    messagingSenderId: '871968891803',
    projectId: 'cloud-uha',
    authDomain: 'cloud-uha.firebaseapp.com',
    storageBucket: 'cloud-uha.appspot.com',
    measurementId: 'G-TFE3D4E0CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgaq4GfwCTtZ7u5ktKYELh8rUuyqGcEPc',
    appId: '1:871968891803:android:08db5f74d97555fa02f73e',
    messagingSenderId: '871968891803',
    projectId: 'cloud-uha',
    storageBucket: 'cloud-uha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVcfcYGnlbZiWBJpljoAAoba3iWZTkqlw',
    appId: '1:871968891803:ios:041d9d7b84caf48d02f73e',
    messagingSenderId: '871968891803',
    projectId: 'cloud-uha',
    storageBucket: 'cloud-uha.appspot.com',
    iosBundleId: 'com.example.finalProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVcfcYGnlbZiWBJpljoAAoba3iWZTkqlw',
    appId: '1:871968891803:ios:331a59885e81011302f73e',
    messagingSenderId: '871968891803',
    projectId: 'cloud-uha',
    storageBucket: 'cloud-uha.appspot.com',
    iosBundleId: 'com.example.finalProj.RunnerTests',
  );
}
